import { ReviewTask } from "./types";

export const AVAILABLE_PROJECTS_LIST = [
  { id: "p1", name: "特唯普上海静安店 (张店长)", category: "线下门店KOS", activeNotes: 18 },
  { id: "p2", name: "特唯普官方旗舰店", category: "品牌自播/官方矩阵", activeNotes: 24 },
  { id: "p3", name: "幼犬换粮体验官测评包", category: "KOC/消费者测评", activeNotes: 14 },
  { id: "p4", name: "三亚海棠湾直营店", category: "标杆门店KOS", activeNotes: 22 },
  { id: "p5", name: "青岛万象城体验店", category: "线下门店KOS", activeNotes: 16 },
  { id: "p6", name: "杭州西湖概念店", category: "线下门店KOS", activeNotes: 15 },
  { id: "p7", name: "金毛垂直犬种矩阵号", category: "自有矩阵号", activeNotes: 12 },
];

export const INITIAL_REVIEW_TASKS: ReviewTask[] = [
  {
    id: "rev-task-1",
    title: "Q2 会员增长复盘",
    dateRange: {
      start: "2026-06-01",
      end: "2026-06-30",
      label: "2026-06-01 至 2026-06-30",
    },
    mode: "multi",
    projectIds: ["p4", "p5", "p6"],
    projectNames: ["三亚海棠湾直营店", "青岛万象城体验店", "杭州西湖概念店"],
    targetObjective: "benchmark",
    targetObjectiveLabel: "横向比较 & 会员增长",
    goalDescription: "分析跨区域门店会员增长与私信转化变化，找出下滑原因与可复制标杆机会",
    status: "completed",
    statusText: "已完成",
    updatedAt: "4 分钟前",
    createdAt: "2026-07-02 10:24",
    activeVersionId: "v2",
    historyVersions: [
      {
        id: "v2",
        versionName: "v2.0 用户编辑确认版本",
        versionTag: "当前最新",
        createdAt: "2026-07-03 16:40",
        createdBy: "张操盘 (运营负责人)",
        dataCutoff: "2026-06-30 23:59",
        status: "published",
        changelog: "确认了三亚店可复用打法，并将‘高转化承接优化’加入执行中心",
        summarySnapshot: "跨3个项目对比完毕，识别出三亚店在‘顾问式答疑’转化率高达 22.4%，输出4条行动建议。",
      },
      {
        id: "v1",
        versionName: "v1.0 Agent 自动初版报告",
        versionTag: "AI生成版",
        createdAt: "2026-07-02 10:35",
        createdBy: "复盘分析 Agent 集群",
        dataCutoff: "2026-06-30 23:59",
        status: "archived",
        changelog: "系统自动完成数据采集与6个Agent任务流分析",
        summarySnapshot: "初次生成跨项目综合分析报告，发现青岛店私信漏斗流失严重。",
      },
    ],
    progressSteps: [
      {
        id: "step-1",
        type: "completed",
        statusLabel: "已完成",
        title: "基础数据采集与多端同步",
        description: "已汇总 3 个门店项目在小红书、来客私信与微信社群的近 30 天全量数据 (共 58 篇笔记，1,420 条私信线索)",
        actionText: "查看数据源",
        actionType: "view_log",
        agentName: "数据采集 Agent",
      },
      {
        id: "step-2",
        type: "completed",
        statusLabel: "已完成",
        title: "全链路转化漏斗计算",
        description: "完成曝光-阅读-互动-私信-核销五层漏斗测算，对比各区域转化差异",
        actionText: "查看计算细节",
        actionType: "view_log",
        agentName: "指标分析 Agent",
      },
      {
        id: "step-3",
        type: "completed",
        statusLabel: "已完成",
        title: "高意向用户群体洞察",
        description: "识别出‘幼犬断奶新手’与‘软便敏感体质宠主’咨询意愿最高 (占比 64.2%)",
        actionText: "查看画像详情",
        actionType: "view_log",
        agentName: "用户洞察 Agent",
      },
      {
        id: "step-4",
        type: "completed",
        statusLabel: "已完成",
        title: "策略建议输出与动作沉淀",
        description: "已生成 4 条具体可落地运营动作，其中 2 条已同步至执行中心",
        actionText: "查看建议",
        actionType: "view_log",
        agentName: "策略建议 Agent",
      },
    ],
    coreConclusions: {
      overallPerformance: {
        status: "up",
        title: "曝光稳定上升，但私信承接效率分化",
        description: "三店总曝光环比增长 +16.8%，但私信咨询有效线索转化率在不同门店出现显著差距 (三亚 22.4% vs 青岛 8.1%)。",
        metricBadge: "总曝光 +16.8%",
        metricDiff: "总线索 1,420 条",
      },
      mainIssue: {
        title: "内容互动正常，但青岛/杭州私信转化偏低",
        description: "高互动笔记评论区未及时建立专人一对一顾问答疑机制，导致 42% 的高意向潜客在评论区流失。",
        cause: "缺乏标准顾问留资SOP，客服响应时效超 45 分钟",
        stage: "私信承接与转化环节",
      },
      keyOpportunity: {
        title: "专业测评与7日换粮答疑在高意向宠主中转化极佳",
        description: "三亚店将‘店长真人换粮打卡’与‘便检报告解读’结合，单篇获客成本降低 38%。",
        potentialGain: "预计可带动全店私信转化率提升 15%~20%",
      },
      priorityAction: {
        title: "优先优化高咨询内容的承接链路与话术库",
        description: "统一配置‘幼犬软便自测表’物料，将三亚店成功话术模版同步给青岛与杭州门店。",
        immediateTarget: "缩短响应时间至 5 分钟内，打通来客自动留资",
      },
    },
    crossProjectComparison: {
      projects: [
        {
          id: "p4",
          name: "三亚海棠湾直营店",
          impressions: { val: "18.4万", diff: "↑30%", trend: "up" },
          conversion: { val: "22.4%", diff: "↑22%", trend: "up" },
          interaction: { val: "12,480", diff: "↑18%", trend: "up" },
          leads: { val: "582人", diff: "↑35%", trend: "up" },
          aiJudgeTag: "表现最佳 · 标杆可复用",
          aiJudgeType: "best",
          keyStrength: "店长真人IP出镜 + 便检答疑置顶，私信承接速度均值 3.2 分钟",
          weakness: "视频发布频次略有不足，目前偏图文",
        },
        {
          id: "p5",
          name: "青岛万象城体验店",
          impressions: { val: "14.2万", diff: "↑12%", trend: "up" },
          conversion: { val: "8.1%", diff: "↓8%", trend: "down" },
          interaction: { val: "8,920", diff: "持平", trend: "flat" },
          leads: { val: "310人", diff: "↓14%", trend: "down" },
          aiJudgeTag: "流量正常 · 转化偏弱",
          aiJudgeType: "warning",
          keyStrength: "图文曝光大，活动促销吸引大量基础点赞",
          weakness: "评论区无专业引导，私信大多为泛流量，有效咨询率低",
        },
        {
          id: "p6",
          name: "杭州西湖概念店",
          impressions: { val: "11.6万", diff: "↑8%", trend: "up" },
          conversion: { val: "12.3%", diff: "↑3%", trend: "up" },
          interaction: { val: "6,840", diff: "↓2%", trend: "down" },
          leads: { val: "528人", diff: "↑5%", trend: "up" },
          aiJudgeTag: "运行稳定 · 缺少爆款",
          aiJudgeType: "normal",
          keyStrength: "到店核销率稳定，老客复购高",
          weakness: "新客搜索词覆盖不足，未能吃到换粮搜索红利",
        },
      ],
      aiSummary: {
        bestProject: "三亚海棠湾直营店在全链路各环节指标均领先，尤其在有效私信咨询率达 22.4%（行业均值仅 9.5%）。",
        reusableFactor: "核心成功要素：张店长人设以‘专业营养师’而非‘推销员’身份切入，置顶评论提供免费《科学换粮排雷指南》，引导私信动作自然流畅。",
        weakProjectIssue: "青岛店主要问题在于过度依赖‘买赠活动’噱头，吸引的非精准人群占 55%，且客服平均响应超 50 分钟，流失率极高。",
        overallRecommendation: "建议将三亚店的‘内容选题库 + 评论区答疑SOP + 5分钟私信响应链’整体沉淀为标准打法，一键应用至青岛与杭州门店。",
      },
    },
    agentPipeline: [
      {
        id: "agent-1",
        name: "数据采集 Agent",
        role: "Data Gathering & Extraction",
        status: "completed",
        statusText: "已完成",
        summary: "已从聚光后台、小红书专业号与来客私信系统同步 58 篇笔记全维数据",
        duration: "1.2s",
        outputItems: ["58 篇小红书笔记曝光与互动明细", "1,420 条私信会话及线索标签", "3 组门店客群地域与设备分布"],
        logs: [
          { time: "10:24:02", level: "info", message: "启动数据抓取作业，关联三亚、青岛、杭州三家门店资产" },
          { time: "10:24:03", level: "success", message: "同步小红书笔记数据 58 篇，全部通过质检校验" },
          { time: "10:24:04", level: "success", message: "读取来客私信记录 1,420 条，已清洗无效灌水会话" },
        ],
      },
      {
        id: "agent-2",
        name: "指标分析 Agent",
        role: "Metrics & Funnel Calculation",
        status: "completed",
        statusText: "已完成",
        summary: "完成全周期 ROI、曝光环比、互动成本与线索流转转化率交叉计算",
        duration: "2.4s",
        outputItems: ["跨门店漏斗衰减矩阵表", "单线索获取成本 (CPL) 趋势", "爆款笔记与长尾笔记效益比"],
        logs: [
          { time: "10:24:05", level: "info", message: "计算跨门店曝光环比，三亚 +30%，青岛 +12%，杭州 +8%" },
          { time: "10:24:06", level: "agent", message: "发现青岛店互动到私信转化率仅 3.4%，触发异常偏离预警" },
          { time: "10:24:07", level: "success", message: "指标矩阵生成完毕，置信度 98.4%" },
        ],
      },
      {
        id: "agent-3",
        name: "用户洞察 Agent",
        role: "Audience & Search Intent Miner",
        status: "completed",
        statusText: "已完成",
        summary: "识别出高意向用户集中在‘幼犬喂养新手’与‘软便换粮痛点’群体",
        duration: "3.1s",
        outputItems: ["核心潜客画像标签分布", "搜索高频词云 (软便/适口性/泪痕)", "意向痛点聚类分析报告"],
        logs: [
          { time: "10:24:08", level: "info", message: "分析 1,420 条咨询文本，运行 NLP 语义槽聚类算法" },
          { time: "10:24:09", level: "agent", message: "提取高频关键词：'换粮拉稀' (32%)、'挑食不吃' (26%)、'配料表肉源' (19%)" },
          { time: "10:24:11", level: "success", message: "输出高意向用户特征卡片：22-35岁初次养宠家庭女性为主" },
        ],
      },
      {
        id: "agent-4",
        name: "内容分析 Agent",
        role: "Content & Creative Performance Evaluator",
        status: "completed",
        statusText: "已完成",
        summary: "真实场景测评型内容转化效率是泛科普内容的 2.8 倍",
        duration: "2.8s",
        outputItems: ["Top 5 爆文结构拆解 (标题/封面/前3秒)", "内容形式转化对比 (实测图文 vs 官方宣导)", "评论区有效互动率排序"],
        logs: [
          { time: "10:24:12", level: "info", message: "针对 58 篇笔记内容类型与封面视觉进行分型聚类" },
          { time: "10:24:13", level: "agent", message: "实测打卡类笔记平均完播率/阅读率比品牌官宣高出 41%" },
          { time: "10:24:14", level: "success", message: "归纳出 3 套高效内容模板（便检实测、7日换粮记录、成分对比）" },
        ],
      },
      {
        id: "agent-5",
        name: "转化分析 Agent",
        role: "Lead Conversion & Follow-up Auditor",
        status: "completed",
        statusText: "已完成",
        summary: "私信 5 分钟内响应成交率提升 3.4 倍，自动承接话术有效承接 68% 流量",
        duration: "1.9s",
        outputItems: ["客服响应时效与转化衰减曲线", "话术承接节点转化漏斗", "门店线下核销归因路径"],
        logs: [
          { time: "10:24:15", level: "info", message: "分析来客系统客服会话时间戳与后续核销记录" },
          { time: "10:24:16", level: "agent", message: "青岛店超过 60% 会话发生在晚上 20:00-23:00，此时人工客服离线" },
          { time: "10:24:17", level: "success", message: "建议在夜间时段配置 AI 操盘副手自动应答" },
        ],
      },
      {
        id: "agent-6",
        name: "策略建议 Agent",
        role: "Strategic Action Synthesizer",
        status: "completed",
        statusText: "已完成",
        summary: "输出 4 条优先级行动动作，并已生成执行中心任务草稿",
        duration: "1.5s",
        outputItems: ["4 项结构化建议动作卡片", "跨项目策略复用提案", "预期收益与预算调整测算"],
        logs: [
          { time: "10:24:18", level: "info", message: "综合各 Agent 结论，生成结构化行动指南" },
          { time: "10:24:19", level: "success", message: "完成策略动作打包，已就绪供操盘手一键分发" },
        ],
      },
    ],
    suggestedActions: [
      {
        id: "act-1",
        title: "优化高转化内容承接链路与夜间自动应答",
        target: "缩短线索流失时间，解决青岛与杭州夜间无人接待问题",
        expectedGain: "预计提升私信留资率 +24%，夜间意向客户挽回率 45%",
        priority: "P0",
        category: "转化承接",
        actionType: "plan",
        appliedStatus: "in_plan",
        appliedDestinationLabel: "已纳入下一期方案",
        inExecutionCenter: false,
        reason: "复盘数据显示 42% 的高意向咨询发生在 20:00-24:00，当前缺乏自动化接待导致严重丢单。",
        recommendedSteps: [
          "在来客系统开启 AI 操盘副手夜间自动回复规则",
          "配置《幼犬7日换粮自测表》作为自动承接钩子物料",
          "设定客服次日早 9:00 前一键回访高潜用户",
        ],
      },
      {
        id: "act-2",
        title: "复制三亚店‘店长便检答疑’选题到青岛与杭州",
        target: "升级图文内容质量，从纯促销转向专业顾问信任背书",
        expectedGain: "单篇互动成本预计下降 35%，有效咨询提升 18%",
        priority: "P0",
        category: "内容策略",
        actionType: "note",
        appliedStatus: "in_note",
        appliedDestinationLabel: "已应用到后续笔记",
        inExecutionCenter: false,
        reason: "三亚店该选题转化率达 22.4%，证明专业实测具有高信任度和搜索长尾效应。",
        recommendedSteps: [
          "下发 5 篇《店长换粮打卡》标准模板至青岛、杭州店长账号",
          "补充门店实测视频素材采集任务 (下发至素材中心)",
          "在小红书置顶包含 SGS 检测报告与顾问问卷的笔记",
        ],
      },
      {
        id: "act-3",
        title: "为青岛店配置小红书评论区专业引导 SOP",
        target: "扭转青岛店‘流量大转化低’的倒挂现状",
        expectedGain: "评论区到私信的有效点击率预计从 3.4% 提升至 9.0%",
        priority: "P1",
        category: "账号运营",
        actionType: "plan",
        appliedStatus: "not_applied",
        inExecutionCenter: false,
        reason: "青岛店评论区充斥‘求链接’但无人回复引导，白白浪费已有自然流量。",
        recommendedSteps: [
          "配置 10 套评论区专业科普回复模板",
          "开启评论区关键字自动预警与引导私信提醒",
        ],
      },
      {
        id: "act-4",
        title: "针对‘幼犬软便’核心搜索词建立矩阵卡位包",
        target: "拦截小红书主动搜索高潜流量",
        expectedGain: "搜索推荐流量占比预计从 14% 提升至 30%",
        priority: "P2",
        category: "搜索卡位",
        actionType: "note",
        appliedStatus: "not_applied",
        inExecutionCenter: false,
        reason: "搜索词分析显示‘幼犬软便怎么换粮’月搜索指数达 12.8 万，商业价值极高。",
        recommendedSteps: [
          "在方案中心创建新的专项搜索卡位计划",
          "由矩阵号与 KOC 批量发布 12 篇针对性测评笔记",
        ],
      },
    ],
    analysisDetails: {
      summary: {
        scope: "三亚海棠湾直营店、青岛万象城体验店、杭州西湖概念店",
        target: "Q2 季度跨门店获客复盘与全链路转化归因",
        projectCount: 3,
        timeWindow: "2026-06-01 至 2026-06-30 (共 30 天)",
        dataSource: "小红书专业号后台、聚光推广数据、来客私信系统、有赞核销流水",
        sampleNotesCount: 58,
      },
      diagnoses: [
        {
          issue: "青岛店高曝光低转化，漏斗流失严重",
          cause: "内容选题以打折送礼为主，吸引非目标客群，且评论区缺乏专业营养师答疑闭环。",
          impact: "单线索成本较三亚高出 140%，有效到店核销率仅 1.8%。",
          severity: "high",
          affectedStage: "获客到转化链路",
        },
        {
          issue: "夜间（20:00-24:00）咨询流失率达 58%",
          cause: "线下门店人工客服下班后无 AI 自动承接机制，用户等待超过 2 小时后流失至竞品。",
          impact: "估算每月至少错失 220+ 位高意向幼犬宠主。",
          severity: "high",
          affectedStage: "私信承接阶段",
        },
        {
          issue: "杭州店搜索端长尾收录不足",
          cause: "笔记标题与正文关键词堆砌不规范，未包含小红书搜索高频修饰词（如‘7日换粮法’、‘幼犬粮避坑’）。",
          impact: "发布 7 天后流量快速衰减至 0，无法享受搜索长尾流量。",
          severity: "medium",
          affectedStage: "内容分发与搜索收录",
        },
      ],
      metricShifts: [
        { metric: "跨项目总曝光量", before: "37.8万", current: "44.2万", change: "+16.8%", isGood: true, note: "三亚店高爆文拉动明显" },
        { metric: "全网总互动量 (赞/藏/评)", before: "24,200", current: "28,240", change: "+16.7%", isGood: true, note: "测评类笔记互动率高" },
        { metric: "私信咨询线索量", before: "1,210", current: "1,420", change: "+17.3%", isGood: true, note: "整体咨询量保持平稳上升" },
        { metric: "有效咨询线索转化率", before: "13.2%", current: "14.3%", change: "+1.1%", isGood: true, note: "三亚大幅提升拉高均值，但青岛拖累" },
        { metric: "单线索平均获客成本 (CPL)", before: "¥24.8", current: "¥19.2", change: "-22.5%", isGood: true, note: "自然搜索与KOS自带流量降本" },
        { metric: "客服平均首次响应时间", before: "34分钟", current: "26分钟", change: "-23.5%", isGood: true, note: "仍需进一步缩短至5分钟内" },
      ],
      insights: {
        contentInsight: {
          title: "内容与素材洞察",
          takeaways: [
            "实测真实场景素材（如张店长手把手教温水泡粮、记录便便形状）信任度最高，完播率超 62%。",
            "纯产品棚拍图与包装精修图在小红书被算法标记为商业广告，自然推流受限。",
            "视频前 3 秒出现痛点提问（‘你家幼犬换粮也天天软便？’）的笔记互动率高出 2.3 倍。",
          ],
        },
        userInsight: {
          title: "潜客与意向洞察",
          takeaways: [
            "64% 的咨询宠主为初次养犬（犬龄在 2-6 个月之间），对‘益生菌配方’与‘胃肠耐受’极度敏感。",
            "用户不仅需要买粮，更需要‘科学养宠指导’，愿意为专业顾问的建议支付 15-20% 的品牌溢价。",
            "地域特征：南方城市（三亚、杭州）更关注软便与泪痕，北方（青岛）更关注适口性与性价比。",
          ],
        },
        conversionInsight: {
          title: "私信与转化承接洞察",
          takeaways: [
            "置顶评论引导‘点击主页领免费便检卡’的转化率比正文提及高出 4 倍。",
            "在私信第 1 轮回复中主动询问狗狗年龄与品种的对话，后续留资率达 78%。",
            "夜间自动化承接并赠送新客试吃装礼券，可将次日到店率提升 31%。",
          ],
        },
      },
      strategicGuidelines: [
        {
          title: "全店推行‘KOS 专业营养师人设’打法",
          detail: "禁止各门店发布纯粹硬广宣传单，将所有账号定位为‘帮助新手铲屎官少走弯路的技术流店长’。",
          actionSteps: ["统一拍摄模板", "每周组织 1 次门店营养知识线上培训", "考核指标从发文量转向有效咨询率"],
        },
        {
          title: "打通 AI 操盘副手 24 小时全天候智能承接",
          detail: "无缝对接来客私信与企业微信，实现夜间自动应答、用户档案自动打标与高潜商机即时推送。",
          actionSteps: ["配置夜间 AI 应答知识库", "设置 5 分钟超时未回复自动转接机制", "每周复盘一次未成交对话"],
        },
      ],
      finalConclusion: "本期复盘表明：品牌依靠三亚店验证了‘KOS 真实测评 + 顾问答疑 + 快速承接’的高转化闭环。下阶段重点在于迅速将该模式规模化复制至青岛与杭州，重点补齐夜间自动承接与搜索词卡位，预计在 Q3 可实现有效线索翻倍增长。",
    },
  },
  {
    id: "rev-task-2",
    title: "8月幼犬换粮矩阵攻坚复盘",
    dateRange: {
      start: "2026-08-01",
      end: "2026-08-20",
      label: "2026-08-01 至 2026-08-20",
    },
    mode: "single",
    projectIds: ["p1"],
    projectNames: ["特唯普上海静安店 (张店长)"],
    targetObjective: "content_strategy",
    targetObjectiveLabel: "内容策略 & 矩阵爆文",
    goalDescription: "复盘 8 月份针对幼犬换粮期打法的内容表现，评估店长号与矩阵号协同效益",
    status: "analyzing",
    statusText: "分析中",
    updatedAt: "刚刚",
    createdAt: "2026-08-20 14:10",
    activeVersionId: "v1",
    historyVersions: [
      {
        id: "v1",
        versionName: "v1.0 实时计算任务",
        versionTag: "运行中",
        createdAt: "2026-08-20 14:10",
        createdBy: "张操盘 (发起任务)",
        dataCutoff: "2026-08-20 14:00",
        status: "draft",
        changelog: "初始化单项目复盘任务，Agent 正在并发分析中",
        summarySnapshot: "正在分析 18 篇已发布笔记与 420 条私信转化记录...",
      },
    ],
    progressSteps: [
      {
        id: "step-201",
        type: "completed",
        statusLabel: "已完成",
        title: "基础数据汇总已完成",
        description: "已同步静安店 18 篇小红书笔记的全部阅读、完播、点赞及收藏数据",
        actionText: "查看数据",
        actionType: "view_log",
        agentName: "数据采集 Agent",
      },
      {
        id: "step-202",
        type: "analyzing",
        statusLabel: "分析中",
        title: "内容效果分析 Agent 正在生成结论",
        description: "正在对 4 篇爆文与 14 篇常规笔记的脚本结构进行语义归因，预计耗时 15 秒",
        actionText: "查看执行日志",
        actionType: "view_log",
        agentName: "内容分析 Agent",
      },
      {
        id: "step-203",
        type: "confirm",
        statusLabel: "待确认",
        title: "确认是否纳入 7 月同期历史方案数据？",
        description: "纳入 7 月历史数据可生成环比增长对照，有助于明确打法迭代成效",
        actionText: "确认纳入",
        actionType: "confirm",
        agentName: "指标分析 Agent",
      },
    ],
    coreConclusions: {
      overallPerformance: {
        status: "up",
        title: "爆文产出率大幅提升，单篇互动均值超 1,200",
        description: "8月共发布 18 篇笔记，其中 4 篇进入平台二级热推池，互动总量环比 7 月提升 +44.2%。",
        metricBadge: "爆文率 22.2%",
        metricDiff: "总曝光 21.6万",
      },
      mainIssue: {
        title: "部分长尾笔记标题过长，搜索收录率仅 40%",
        description: "标题文字超过 22 字导致在小红书双列信息流中被折叠，影响点击率。",
        cause: "文案未遵循 18 字黄金标题规范",
        stage: "内容制作与发布",
      },
      keyOpportunity: {
        title: "‘换粮排气与软便改善’实录视频成为绝对流量引擎",
        description: "该类视频的完播率高达 54%，带来 62% 的全店私信咨询。",
        potentialGain: "建议增加此类视频在内容库中的配比至 50%",
      },
      priorityAction: {
        title: "下发视频分镜模板至素材拍摄中心",
        description: "标准化‘痛点展示-便检对比-成分分析-换粮建议’四段式短视频结构。",
        immediateTarget: "本周内产出 6 条高质量实测视频",
      },
    },
    agentPipeline: [
      {
        id: "ag-21",
        name: "数据采集 Agent",
        role: "Data Extraction",
        status: "completed",
        statusText: "已完成",
        summary: "18 篇笔记与 420 条私信数据采集完毕",
        duration: "0.8s",
        outputItems: ["18 篇笔记基础表现数据", "420 条私信互动记录"],
        logs: [{ time: "14:10:02", level: "success", message: "数据抓取完成" }],
      },
      {
        id: "ag-22",
        name: "内容分析 Agent",
        role: "Creative Evaluation",
        status: "running",
        statusText: "正在分析中",
        summary: "正在评估 18 篇笔记的情感极性与转评比...",
        duration: "进行中 (已用时 8s)",
        outputItems: ["爆文结构提取中..."],
        logs: [
          { time: "14:10:05", level: "info", message: "正在对视频帧画面与文本进行多模态对齐" },
          { time: "14:10:12", level: "agent", message: "初步发现：前3秒出现狗狗实操的笔记播放完成率高 38%" },
        ],
      },
      {
        id: "ag-23",
        name: "转化分析 Agent",
        role: "Conversion Funnel",
        status: "pending",
        statusText: "等待前置任务",
        summary: "等待内容分析完成后自动启动",
        duration: "0s",
        outputItems: [],
        logs: [],
      },
      {
        id: "ag-24",
        name: "策略建议 Agent",
        role: "Strategy Synthesis",
        status: "pending",
        statusText: "等待前置任务",
        summary: "等待全量数据归集后生成建议动作",
        duration: "0s",
        outputItems: [],
        logs: [],
      },
    ],
    suggestedActions: [
      {
        id: "act-201",
        title: "规范小红书标题在 18 字以内并强化痛点词",
        target: "避免信息流标题被折叠，提升笔记点击率 (CTR)",
        expectedGain: "预计点击率从 4.2% 提升至 6.5%",
        priority: "P0",
        category: "内容制作",
        actionType: "note",
        appliedStatus: "not_applied",
        inExecutionCenter: false,
        reason: "分析显示超过 20 字的标题在移动端有 60% 概率截断核心修饰词。",
        recommendedSteps: [
          "更新 AI 文本生成模型的标题长度约束参数",
          "在发文审核抽检中增加标题字数合规检查",
        ],
      },
      {
        id: "act-202",
        title: "加大‘7日换粮实测视频’生产排期",
        target: "持续获取高信任度高意向客流",
        expectedGain: "预计私信咨询总量增加 +30%",
        priority: "P1",
        category: "素材调度",
        actionType: "plan",
        appliedStatus: "in_plan",
        appliedDestinationLabel: "已纳入下一期方案",
        inExecutionCenter: false,
        reason: "此类内容在张店长人设下具备天然真实度，完播率与互动率双高。",
        recommendedSteps: [
          "向素材中心指派 4 组真实换粮视频拍摄任务",
          "关联张店长官方账号发布",
        ],
      },
    ],
    analysisDetails: {
      summary: {
        scope: "特唯普上海静安店 (张店长)",
        target: "8 月换粮期内容矩阵成效与爆款归因",
        projectCount: 1,
        timeWindow: "2026-08-01 至 2026-08-20",
        dataSource: "小红书专业号后台、张店长主页私信",
        sampleNotesCount: 18,
      },
      diagnoses: [
        {
          issue: "部分标题过长导致信息流点击率偏低",
          cause: "人工拟定标题时塞入过多副标题，未做字数控制。",
          impact: "损失约 25% 的自然信息流曝光点击机会。",
          severity: "medium",
          affectedStage: "封面与标题制作",
        },
      ],
      metricShifts: [
        { metric: "笔记总曝光", before: "15.0万", current: "21.6万", change: "+44.0%", isGood: true, note: "爆款拉动" },
        { metric: "平均阅读互动率", before: "6.8%", current: "8.9%", change: "+2.1%", isGood: true, note: "实测内容质量提升" },
        { metric: "私信有效线索", before: "280", current: "420", change: "+50.0%", isGood: true, note: "留资增长亮眼" },
      ],
      insights: {
        contentInsight: {
          title: "内容洞察",
          takeaways: [
            "实拍狗狗真实进食与换粮便检的视频内容，比纯科普图文带来 3 倍以上的私信咨询。",
            "封面采用‘对比大字报 + 真实狗狗实拍’的点击率最高。",
          ],
        },
        userInsight: {
          title: "用户洞察",
          takeaways: [
            "上海静安周边宠主对‘进口溯源’与‘益生菌配比’提问频次最高。",
          ],
        },
        conversionInsight: {
          title: "转化洞察",
          takeaways: [
            "张店长在私信中直接给出换粮食谱，用户到店意愿达 85%。",
          ],
        },
      },
      strategicGuidelines: [
        {
          title: "建立‘实测视频 + 顾问答疑’双轮驱动",
          detail: "店长号专注高信任度实测内容，矩阵号负责长尾搜索词覆盖。",
          actionSteps: ["下发脚本模板", "建立每日私信复盘机制"],
        },
      ],
      finalConclusion: "8月攻坚打法验证成功，店长真人IP爆发力显著，下阶段建议继续深化视频实测素材生产。",
    },
  },
  {
    id: "rev-task-3",
    title: "华东线下门店KOS获客复盘",
    dateRange: {
      start: "2026-07-01",
      end: "2026-07-31",
      label: "2026-07-01 至 2026-07-31",
    },
    mode: "multi",
    projectIds: ["p1", "p5", "p6"],
    projectNames: ["特唯普上海静安店", "青岛万象城体验店", "杭州西湖概念店"],
    targetObjective: "conversion",
    targetObjectiveLabel: "门店获客 & 转化分析",
    goalDescription: "评估华东三家直营门店 KOS 账号矩阵的获客成本、私信咨询质量与到店核销",
    status: "exception",
    statusText: "1项异常待处理",
    updatedAt: "18 分钟前",
    createdAt: "2026-08-01 09:30",
    activeVersionId: "v1",
    historyVersions: [
      {
        id: "v1",
        versionName: "v1.0 异常中断版本",
        versionTag: "异常待处理",
        createdAt: "2026-08-01 09:45",
        createdBy: "系统自动触发",
        dataCutoff: "2026-07-31 23:59",
        status: "draft",
        changelog: "青岛门店缺少小红书评论区互动详情数据，转化分析 Agent 暂停",
        summarySnapshot: "数据不完整，已完成 2 个项目分析，青岛项目等待数据补齐。",
      },
    ],
    progressSteps: [
      {
        id: "step-301",
        type: "completed",
        statusLabel: "已完成",
        title: "上海与杭州门店数据抓取完毕",
        description: "已成功解析 34 篇笔记与 860 条私信数据",
        actionText: "查看已采集数据",
        actionType: "view_log",
        agentName: "数据采集 Agent",
      },
      {
        id: "step-302",
        type: "blocked",
        statusLabel: "阻断",
        title: "青岛万象城店缺少评论区互动数据，无法完成跨项目对比",
        description: "该门店小红书专业号授权已过期，导致评论区明细无法同步",
        actionText: "去重新授权 / 补齐数据",
        actionType: "supplement_data",
        agentName: "数据采集 Agent",
      },
      {
        id: "step-303",
        type: "analyzing",
        statusLabel: "分析中",
        title: "其余项目指标分析已就绪，等待全量对齐",
        description: "上海与杭州门店指标已完成初步计算",
        actionText: "查看初步结论",
        actionType: "view_log",
        agentName: "指标分析 Agent",
      },
    ],
    coreConclusions: {
      overallPerformance: {
        status: "stable",
        title: "华东整体到店核销稳定，数据缺失影响完整归因",
        description: "已同步的两家门店 7 月到店核销率均达 16.5%，青岛店由于数据授权异常暂未计入。",
        metricBadge: "核销率 16.5%",
        metricDiff: "总到店 340 人",
      },
      mainIssue: {
        title: "青岛万象城店数据链路断开，影响跨店对比准确性",
        description: "第三方授权过期导致无法抓取近 15 天评论互动与私信时效数据。",
        cause: "门店账号密码变更后未及时在系统更新授权",
        stage: "数据采集与基础设施",
      },
      keyOpportunity: {
        title: "静安店老客转介绍率高达 28%，可形成裂变手册",
        description: "张店长通过微信社群提供定期毛发健康咨询，带动老客转介绍新宠主。",
        potentialGain: "可复制为全华东门店标准私域裂变机制",
      },
      priorityAction: {
        title: "立即重新授权青岛门店账号，并补齐近 30 天缺失数据",
        description: "恢复数据同步后，系统将自动重新触发全量跨项目对比任务流。",
        immediateTarget: "完成青岛专业号重新授权",
      },
    },
    crossProjectComparison: {
      projects: [
        {
          id: "p1",
          name: "特唯普上海静安店",
          impressions: { val: "16.8万", diff: "↑15%", trend: "up" },
          conversion: { val: "18.2%", diff: "↑12%", trend: "up" },
          interaction: { val: "9,600", diff: "↑10%", trend: "up" },
          leads: { val: "480人", diff: "↑18%", trend: "up" },
          aiJudgeTag: "表现良好 · 持续增长",
          aiJudgeType: "best",
          keyStrength: "私信回复快，老客社群粘性高",
          weakness: "活动笔记较多，纯知识干货略减",
        },
        {
          id: "p6",
          name: "杭州西湖概念店",
          impressions: { val: "10.4万", diff: "↑5%", trend: "up" },
          conversion: { val: "14.1%", diff: "持平", trend: "flat" },
          interaction: { val: "5,800", diff: "↓3%", trend: "down" },
          leads: { val: "380人", diff: "↑2%", trend: "up" },
          aiJudgeTag: "运行平稳",
          aiJudgeType: "normal",
          keyStrength: "线下环境优质，到店核销意愿强",
          weakness: "小红书发文频次偏低 (每周仅2篇)",
        },
        {
          id: "p5",
          name: "青岛万象城体验店",
          impressions: { val: "数据待补齐", diff: "-", trend: "flat" },
          conversion: { val: "数据待补齐", diff: "-", trend: "flat" },
          interaction: { val: "数据待补齐", diff: "-", trend: "flat" },
          leads: { val: "数据待补齐", diff: "-", trend: "flat" },
          aiJudgeTag: "数据异常 · 需重新授权",
          aiJudgeType: "warning",
          keyStrength: "待同步后评估",
          weakness: "账号授权断开，缺失最近15天数据",
        },
      ],
      aiSummary: {
        bestProject: "上海静安店在华东区表现最为均衡，获客成本低且老客复购高。",
        reusableFactor: "张店长人设的社群粘性与一对一私信咨询极具信任感。",
        weakProjectIssue: "青岛万象城店由于授权断开导致数据孤岛，需尽快修复。",
        overallRecommendation: "补齐青岛店数据后可形成完整的华东区直营门店横向对比方案。",
      },
    },
    agentPipeline: [
      {
        id: "ag-31",
        name: "数据采集 Agent",
        role: "Data Extraction",
        status: "exception",
        statusText: "遇到异常",
        summary: "青岛万象城店授权过期 (Token Invalid)，静安与西湖店采集成功",
        duration: "0.5s",
        outputItems: ["静安店数据集 (34篇)", "西湖店数据集 (18篇)"],
        anomalyNotice: "青岛万象城店小红书专业号授权失效，请点击‘去重新授权’",
        logs: [
          { time: "09:30:02", level: "info", message: "开始连接三家门店小红书开放平台 API" },
          { time: "09:30:04", level: "warn", message: "青岛万象城店返回 401 Unauthorized，授权令牌已失效" },
          { time: "09:30:05", level: "info", message: "阻断分析流，生成待办提醒" },
        ],
      },
      {
        id: "ag-32",
        name: "指标分析 Agent",
        role: "Metrics Calculator",
        status: "pending",
        statusText: "挂起等待",
        summary: "等待前置数据采集异常解决后继续",
        duration: "0s",
        outputItems: [],
        logs: [],
      },
    ],
    suggestedActions: [
      {
        id: "act-301",
        title: "重新授权青岛万象城店小红书专业号",
        target: "恢复华东区数据采集完整性",
        expectedGain: "立即解锁青岛店全量分析结论与对比报告",
        priority: "P0",
        category: "系统设置",
        actionType: "plan",
        appliedStatus: "not_applied",
        inExecutionCenter: false,
        reason: "数据缺失导致无法输出综合 ROI 归因结论。",
        recommendedSteps: [
          "前往‘账号资产’模块重新绑定青岛店小红书专业号",
          "在复盘详情页点击‘重试采集’",
        ],
      },
    ],
    analysisDetails: {
      summary: {
        scope: "华东直营门店 (上海/杭州/青岛)",
        target: "7 月门店 KOS 获客成效与私信承接质量复盘",
        projectCount: 3,
        timeWindow: "2026-07-01 至 2026-07-31",
        dataSource: "小红书专业号、来客私信、门店核销",
        sampleNotesCount: 52,
      },
      diagnoses: [
        {
          issue: "青岛门店数据授权中断",
          cause: "账号密码变更后未同步更新系统授权令牌。",
          impact: "华东区数据聚合完整度仅为 66.7%。",
          severity: "high",
          affectedStage: "数据接入层",
        },
      ],
      metricShifts: [
        { metric: "华东区总曝光", before: "24.5万", current: "27.2万 (部分)", change: "+11.0%", isGood: true, note: "两店数据" },
        { metric: "总留资人数", before: "760", current: "860 (部分)", change: "+13.1%", isGood: true, note: "静安店贡献主力" },
      ],
      insights: {
        contentInsight: {
          title: "内容洞察",
          takeaways: ["静安店真人出镜笔记表现优于西湖店图文。"],
        },
        userInsight: {
          title: "用户洞察",
          takeaways: ["华东高净值宠主对原料产地与SGS质检报告极为重视。"],
        },
        conversionInsight: {
          title: "转化洞察",
          takeaways: ["私信提供‘到店免费体验粮’的转化率最高。"],
        },
      },
      strategicGuidelines: [
        {
          title: "建立门店账号授权监控预警机制",
          detail: "授权过期前 3 天发送提醒，防止复盘断点。",
          actionSteps: ["设置短信预警", "配置多管理员备份权限"],
        },
      ],
      finalConclusion: "华东区门店表现总体稳健，请优先处理青岛店授权异常以获取完整横向分析报告。",
    },
  },
  {
    id: "rev-task-4",
    title: "品牌自播与小红书搜索卡位复盘",
    dateRange: {
      start: "2026-07-15",
      end: "2026-08-15",
      label: "2026-07-15 至 2026-08-15",
    },
    mode: "single",
    projectIds: ["p2"],
    projectNames: ["特唯普官方旗舰店"],
    targetObjective: "project_diagnosis",
    targetObjectiveLabel: "搜索卡位 & 品牌自播",
    goalDescription: "复盘官方旗舰店在小红书核心搜索词卡位与自播间引流转化成效",
    status: "completed",
    statusText: "已完成",
    updatedAt: "2 天前",
    createdAt: "2026-08-16 11:20",
    activeVersionId: "v1",
    historyVersions: [
      {
        id: "v1",
        versionName: "v1.0 官方定稿版本",
        versionTag: "已归档",
        createdAt: "2026-08-16 11:45",
        createdBy: "复盘分析 Agent",
        dataCutoff: "2026-08-15 23:59",
        status: "published",
        changelog: "已完成全周期搜索卡位归因，核心词占位率提升 35%",
        summarySnapshot: "官方旗舰店成功在‘特唯普幼犬粮’与‘低温烘焙粮排雷’两大关键词占据前 3 席位。",
      },
    ],
    progressSteps: [
      {
        id: "step-401",
        type: "completed",
        statusLabel: "已完成",
        title: "全周期搜索卡位快照抓取完毕",
        description: "连续 30 天监控小红书 12 个核心关键词搜索结果前 50 位排名",
        actionText: "查看搜索排位",
        actionType: "view_log",
        agentName: "数据采集 Agent",
      },
      {
        id: "step-402",
        type: "completed",
        statusLabel: "已完成",
        title: "自然搜索与付费投流 ROI 交叉比对完成",
        description: "测算出自然搜索带来的私信咨询占比达 48%，单客获客成本低至 ¥12.4",
        actionText: "查看明细",
        actionType: "view_log",
        agentName: "指标分析 Agent",
      },
    ],
    coreConclusions: {
      overallPerformance: {
        status: "up",
        title: "核心品牌词搜索卡位率达 85%，长尾流量带来稳定进店",
        description: "通过官方号与矩阵号协同发文，‘特唯普’品牌词相关搜索结果前 10 席中占据 6 席。",
        metricBadge: "卡位率 85%",
        metricDiff: "日均搜索进店 320+",
      },
      mainIssue: {
        title: "竞品在‘幼犬换粮’泛词下投放力度加大，部分排位下滑",
        description: "竞品通过聚光信息流强投，将我方在‘幼犬软便怎么办’泛词下的排位从第 2 名挤压至第 5 名。",
        cause: "未配置竞品防御性投放策略",
        stage: "搜索投放与关键词维护",
      },
      keyOpportunity: {
        title: "‘低温烘焙粮’品类词搜索增速明显，适合作为主攻词",
        description: "该词近 30 天小红书搜索热度环比增长 +68%，目前竞品防守薄弱。",
        potentialGain: "预计可抢占 30% 以上的品类新增意向客流",
      },
      priorityAction: {
        title: "在方案中心启动‘低温烘焙粮’品类词攻坚专项计划",
        description: "组织 10 篇针对烘焙工艺与消化吸收率的深度测评图文，抢占搜索前排。",
        immediateTarget: "两周内攻占该词前 3 席位",
      },
    },
    agentPipeline: [
      {
        id: "ag-41",
        name: "数据采集 Agent",
        role: "Search Snapshot",
        status: "completed",
        statusText: "已完成",
        summary: "12 个关键词共计 360 次搜索快照抓取完毕",
        duration: "1.4s",
        outputItems: ["搜索排名位移趋势图", "竞品出价与拦截监控报告"],
        logs: [{ time: "11:20:02", level: "success", message: "搜索快照采集完毕" }],
      },
      {
        id: "ag-42",
        name: "策略建议 Agent",
        role: "Keyword Defense",
        status: "completed",
        statusText: "已完成",
        summary: "输出 2 条搜索卡位调整建议",
        duration: "1.1s",
        outputItems: ["关键词预算调优建议", "攻防词库清单"],
        logs: [{ time: "11:20:10", level: "success", message: "策略输出完毕" }],
      },
    ],
    suggestedActions: [
      {
        id: "act-401",
        title: "针对‘低温烘焙粮’部署 10 篇搜索卡位图文",
        target: "抢占品类上升期搜索红利",
        expectedGain: "预计搜索进店量日均提升 +150 人",
        priority: "P0",
        category: "搜索卡位",
        actionType: "note",
        appliedStatus: "in_note",
        appliedDestinationLabel: "已应用到后续笔记",
        inExecutionCenter: false,
        reason: "烘焙粮品类词搜索涨幅高且竞争小，具备极高 ROI 潜力。",
        recommendedSteps: [
          "在方案中心创建‘烘焙粮专项搜索’方案",
          "下发 10 篇笔记至矩阵号发布",
        ],
      },
    ],
    analysisDetails: {
      summary: {
        scope: "特唯普官方旗舰店",
        target: "小红书搜索卡位与旗舰店自播引流复盘",
        projectCount: 1,
        timeWindow: "2026-07-15 至 2026-08-15",
        dataSource: "聚光后台、千川搜索、官方旗舰店数据",
        sampleNotesCount: 24,
      },
      diagnoses: [
        {
          issue: "泛词‘幼犬软便’排位被竞品信息流挤压",
          cause: "未开启竞品拦截词防守出价。",
          impact: "泛词进店量环比下滑 12%。",
          severity: "medium",
          affectedStage: "关键词竞价与内容卡位",
        },
      ],
      metricShifts: [
        { metric: "品牌词前3占位率", before: "70%", current: "85%", change: "+15.0%", isGood: true, note: "官方号矩阵优势" },
        { metric: "搜索自然引流进店", before: "6,800", current: "9,600", change: "+41.2%", isGood: true, note: "长尾词积累" },
      ],
      insights: {
        contentInsight: {
          title: "内容洞察",
          takeaways: ["官方背书配合 SGS 证书的笔记在搜索结果中点击率高出 40%。"],
        },
        userInsight: {
          title: "用户洞察",
          takeaways: ["搜索‘低温烘焙’的用户客单价是普通搜索用户的 1.6 倍。"],
        },
        conversionInsight: {
          title: "转化洞察",
          takeaways: ["通过搜索卡位进入直播间的用户留存时长高出 55%。"],
        },
      },
      strategicGuidelines: [
        {
          title: "深化‘品牌词强占位 + 品类词快拦截’策略",
          detail: "用官方号稳固品牌词，矩阵号包抄品类词与痛点词。",
          actionSteps: ["每周监控一次排位", "动态调整聚光出价"],
        },
      ],
      finalConclusion: "搜索卡位战略初具规模，建议扩大至烘焙粮品类词，持续拉升自然流量池。",
    },
  },
];
