import React, { useState } from 'react';
import { MaterialAsset } from './types';
import {
  X,
  Sparkles,
  Bot,
  Layers,
  Send,
  Check,
  RefreshCw,
  Image as ImageIcon,
  ArrowRight,
  Info,
  ShieldCheck,
  CheckCircle2,
  Sliders
} from 'lucide-react';

interface AICoverStudioModalProps {
  isOpen: boolean;
  onClose: () => void;
  parentMaterial?: MaterialAsset | null;
  availableMaterials: MaterialAsset[];
  onConfirmNewMaterial: (newAsset: MaterialAsset) => void;
}

export const AICoverStudioModal: React.FC<AICoverStudioModalProps> = ({
  isOpen,
  onClose,
  parentMaterial,
  availableMaterials,
  onConfirmNewMaterial
}) => {
  if (!isOpen) return null;

  const [promptInput, setPromptInput] = useState<string>(
    parentMaterial
      ? `基于素材【${parentMaterial.name}】，替换为日系清爽阳光木桌背景，在顶部排版【幼犬换粮必看3招】，适配小红书3:4黄金比例。`
      : '请为【幼犬换粮软便卡位项目】的第2篇小红书笔记推荐并制作高点击率封面。'
  );

  const [isGenerating, setIsGenerating] = useState<boolean>(false);
  const [selectedCandidateIndex, setSelectedCandidateIndex] = useState<number>(0);

  // Candidates state generated by Agent
  const [candidates, setCandidates] = useState<
    Array<{
      id: string;
      title: string;
      url: string;
      service: string;
      modificationSummary: string;
      reason: string;
      aspectRatio: '3:4';
    }>
  >([
    {
      id: 'CAND-01',
      title: '日系温馨阳光桌面 + 3:4顶部花字',
      url: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&auto=format&fit=crop&q=80',
      service: '即梦-AIGC v2.1',
      modificationSummary: '画面重构：将纯蓝背景替换为日系浅木桌；清理背景杂物；顶部留白30%并叠加【换粮不软便】高清文案。',
      reason: '高置信度推荐：符合账号【极宠家·KOS张店长】人设，且色调匹配过往4.8%点击率爆款封面规律。',
      aspectRatio: '3:4'
    },
    {
      id: 'CAND-02',
      title: '高对比警示醒目风 + 侧边花字',
      url: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=600&auto=format&fit=crop&q=80',
      service: 'Orshot-Engine v1.8',
      modificationSummary: '场景变化：扩展两侧视角；增强主粮质感；左侧排版黄色警示标【幼犬软便救急】。',
      reason: '适合测评类痛点卡位，强化主粮与进食场景对比。',
      aspectRatio: '3:4'
    }
  ]);

  const handleGenerate = () => {
    setIsGenerating(true);
    setTimeout(() => {
      setIsGenerating(false);
    }, 1200);
  };

  const handleConfirmCandidate = () => {
    const chosen = candidates[selectedCandidateIndex];
    const newAsset: MaterialAsset = {
      id: `MAT-2026-DERIV-${Date.now().toString().slice(-4)}`,
      name: chosen.title,
      url: chosen.url,
      aspectRatio: chosen.aspectRatio,
      fileType: 'image',
      fileSize: '3.2 MB',
      resolution: '3000x4000',

      category: 'derived_material',
      status: 'pending_acceptance', // Rule: AI derived results re-enter 待验收
      materialUse: 'cover',
      sourceType: 'ai_derived',
      sourceLabel: `AI衍生 (${chosen.service})`,

      uploader: 'AI Agent (操盘手确认)',
      uploadTime: new Date().toISOString().replace('T', ' ').slice(0, 19),
      sourceProject: parentMaterial?.sourceProject || '幼犬换粮软便卡位项目',

      usageRelation: undefined,

      performance: {
        hasBackendData: false,
        performanceType: 'none'
      },

      lineage: {
        parentId: parentMaterial?.id,
        parentName: parentMaterial?.name,
        parentUrl: parentMaterial?.url,
        modificationType: chosen.modificationSummary,
        generatorService: chosen.service,
        promptUsed: promptInput
      },

      acceptance: {
        aiRecognition: {
          tag: 'AI识别结果，可修改',
          status: 'passed',
          subject: '衍生封面',
          product: '极宠家·幼犬粮',
          scene: 'AI生成的日系温馨场景',
          composition: '3:4 黄金分割构图',
          lightingColor: '柔和通透自然光'
        },
        manualAcceptance: {
          operatorName: '操盘手',
          time: new Date().toISOString().replace('T', ' ').slice(0, 16),
          passed: true,
          comment: '经AI制作封面工作台生成并初步确认，进入待验收状态'
        }
      }
    };

    onConfirmNewMaterial(newAsset);
    onClose();
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/40 backdrop-blur-sm p-4">
      <div className="w-[960px] max-w-full h-[680px] max-h-[90vh] bg-surface rounded-xl shadow-2xl border border-border-default flex flex-col overflow-hidden animate-in zoom-in-95 duration-150">
        
        {/* Header */}
        <div className="h-14 px-6 border-b border-border-default flex items-center justify-between shrink-0 bg-surface-subtle">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-surface border border-border-default flex items-center justify-center text-text-primary">
              <Sparkles size={18} />
            </div>
            <div>
              <h3 className="text-[15px] font-semibold text-text-primary tracking-tight">
                AI 制作封面工作台
              </h3>
              <p className="text-[11px] text-text-tertiary">
                Agent 协同工作流：自动装载项目打法、品牌 VI、禁用词库与爆款封面历史
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-1.5 text-text-tertiary hover:text-text-primary rounded-md hover:bg-surface-hover transition-colors"
          >
            <X size={18} />
          </button>
        </div>

        {/* Modal Main Content: Split View */}
        <div className="flex-1 flex overflow-hidden">
          
          {/* Left Column: Context & Natural Language Workbench */}
          <div className="w-[380px] border-r border-border-default flex flex-col bg-surface-subtle p-5 overflow-y-auto space-y-4">
            
            {/* Auto-Loaded Agent Context */}
            <div className="space-y-2">
              <span className="text-[11px] font-semibold text-text-tertiary uppercase tracking-wider block">
                Agent 自动关联上下文
              </span>

              <div className="p-3 bg-surface border border-border-subtle rounded-lg text-[12px] space-y-1.5">
                <div className="flex justify-between">
                  <span className="text-text-tertiary">商家与项目:</span>
                  <span className="font-medium text-text-primary">极宠家 · 幼犬换粮软便卡位</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-text-tertiary">目标账号人设:</span>
                  <span className="text-text-primary">极宠家·KOS张店长 (专业且亲和)</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-text-tertiary">品牌 VI 规范:</span>
                  <span className="text-text-primary">主色 #E63560 / 字体 站酷高端黑</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-text-tertiary">品牌合规:</span>
                  <span className="text-emerald-700 font-medium">已自动开启医疗/违规词过滤</span>
                </div>
              </div>
            </div>

            {/* Parent Material Info if deriving */}
            {parentMaterial ? (
              <div className="space-y-2">
                <span className="text-[11px] font-semibold text-text-tertiary uppercase tracking-wider block">
                  母素材 (衍生源)
                </span>
                <div className="p-2.5 bg-surface border border-border-subtle rounded-lg flex items-center gap-3">
                  <img src={parentMaterial.url} alt="Parent" className="w-12 h-12 object-cover rounded border border-border-subtle shrink-0" />
                  <div className="min-w-0 flex-1 text-[12px]">
                    <span className="font-semibold text-text-primary truncate block">{parentMaterial.name}</span>
                    <span className="text-[11px] text-text-tertiary">{parentMaterial.id} · {parentMaterial.aspectRatio}</span>
                  </div>
                </div>
              </div>
            ) : (
              <div className="p-3 bg-blue-50/60 border border-blue-200/60 rounded-lg text-[12px] text-blue-900 space-y-1">
                <strong className="block font-semibold">可用素材池联动:</strong>
                Agent 已扫描素材库中 {availableMaterials.length} 个可用元件与实拍素材，将优先调用做背景融合与扩图。
              </div>
            )}

            {/* Natural Language Instruction Area */}
            <div className="flex-1 flex flex-col space-y-2 pt-2 border-t border-border-subtle">
              <label className="text-[12px] font-semibold text-text-primary flex items-center justify-between">
                <span>自然语言协同指令</span>
                <span className="text-[11px] text-text-tertiary font-normal">支持直接写制作要求</span>
              </label>

              <textarea
                value={promptInput}
                onChange={(e) => setPromptInput(e.target.value)}
                rows={4}
                className="w-full p-3 bg-surface border border-border-default rounded-lg text-[13px] text-text-primary focus:outline-none focus:border-brand-500 focus:ring-1 focus:ring-brand-500 resize-none"
                placeholder="例如：对已有图片重新构图，清理背景，添加标题文字，调整光影..."
              />

              <button
                onClick={handleGenerate}
                disabled={isGenerating}
                className="w-full py-2.5 bg-action-primary hover:bg-action-primary-hover disabled:opacity-50 text-white rounded-lg text-[13px] font-semibold transition-colors flex items-center justify-center gap-2 shadow-sm"
              >
                {isGenerating ? (
                  <>
                    <RefreshCw size={15} className="animate-spin" />
                    Agent 正在智能构图与渲染...
                  </>
                ) : (
                  <>
                    <Sparkles size={15} />
                    生成封面候选方案
                  </>
                )}
              </button>
            </div>

          </div>

          {/* Right Column: Candidates & Preview */}
          <div className="flex-1 bg-surface p-6 overflow-y-auto flex flex-col justify-between">
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <h4 className="text-[14px] font-semibold text-text-primary flex items-center gap-1.5">
                  <Bot size={16} className="text-text-primary" />
                  Agent 生成的候选方案 ({candidates.length})
                </h4>
                <span className="text-[11px] text-text-tertiary">
                  确认后生成独立素材ID，放入【待验收】池，不覆盖原始素材
                </span>
              </div>

              {/* Candidate Cards Grid */}
              <div className="grid grid-cols-2 gap-4">
                {candidates.map((cand, idx) => {
                  const isSelected = selectedCandidateIndex === idx;
                  return (
                    <div
                      key={cand.id}
                      onClick={() => setSelectedCandidateIndex(idx)}
                      className={`cursor-pointer border rounded-lg overflow-hidden transition-all p-3 flex flex-col justify-between ${
                        isSelected
                          ? 'border-action-primary bg-surface-subtle ring-1 ring-action-primary shadow-md'
                          : 'border-border-default bg-surface hover:border-border-strong'
                      }`}
                    >
                      <div>
                        {/* Preview Image */}
                        <div className="aspect-[3/4] bg-surface-subtle rounded overflow-hidden relative mb-3 border border-border-subtle">
                          <img src={cand.url} alt={cand.title} className="w-full h-full object-cover" />
                          <span className="absolute top-2 left-2 px-1.5 py-0.5 rounded text-[10px] bg-black/70 text-white font-medium">
                            {cand.service}
                          </span>
                          {isSelected && (
                            <span className="absolute top-2 right-2 p-1 rounded-full bg-action-primary text-white shadow">
                              <Check size={12} />
                            </span>
                          )}
                        </div>

                        {/* Title & Summary */}
                        <h5 className="text-[13px] font-semibold text-text-primary mb-1">
                          {cand.title}
                        </h5>
                        <p className="text-[11px] text-text-secondary leading-normal mb-2">
                          {cand.modificationSummary}
                        </p>
                      </div>

                      {/* Rationale */}
                      <div className="p-2 bg-surface-subtle rounded border border-border-subtle text-[11px] text-text-tertiary">
                        <strong className="text-text-primary">适用理由: </strong> {cand.reason}
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>

            {/* Confirmation Footer */}
            <div className="pt-4 border-t border-border-default flex items-center justify-between mt-6">
              <div className="text-[12px] text-text-secondary flex items-center gap-1.5">
                <Info size={14} className="text-text-tertiary shrink-0" />
                <span>
                  当前选中候选 #{candidates[selectedCandidateIndex]?.id}，确定保存后建立父子谱系
                </span>
              </div>

              <div className="flex items-center gap-3">
                <button
                  onClick={onClose}
                  className="px-4 py-2 border border-border-default hover:bg-surface-hover rounded text-[12px] font-medium text-text-primary"
                >
                  取消
                </button>

                <button
                  onClick={handleConfirmCandidate}
                  className="px-5 py-2 bg-action-primary hover:bg-action-primary-hover text-white rounded text-[12px] font-semibold transition-colors flex items-center gap-1.5 shadow-sm"
                >
                  <CheckCircle2 size={15} />
                  确认选择并保存为新素材
                </button>
              </div>
            </div>

          </div>

        </div>

      </div>
    </div>
  );
};
